<a href="https://colab.research.google.com/github/democodext/Hate-Speech-Detaction/blob/Hate_Speech/Hate_Speech_Detaction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **importing labraries**

In [17]:
import pandas as pd
import numpy as np

In [18]:
dataset= pd.read_csv('/content/HateSpeechDatasetBalanced.csv')

In [19]:
dataset

                                                  Content  Label
0       denial of normal the con be asked to comment o...    1.0
1       just by being able to tweet this insufferable ...    1.0
2       that is retarded you too cute to be single tha...    1.0
3       thought of a real badass mongol style declarat...    1.0
4                                     afro american basho    1.0
...                                                   ...    ...
421745  utc name change the article has been changed t...    0.0
421746  charles sumner article hello dr jensen i have ...    0.0
421747  and i really appreciate you for this i have to...    0.0
421748  copyright hi moran i wanted to talk to you abo...    0.0
421749  wikipediaarticles for deletion list of plants ...    NaN

[421750 rows x 2 columns]

In [20]:
dataset.isnull().sum()

Content    0
Label      1
dtype: int64

In [21]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421750 entries, 0 to 421749
Data columns (total 2 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   Content  421750 non-null  object
 1   Label    421749 non-null  float64
dtypes: float64(1), object(1)
memory usage: 6.4+ MB

In [22]:
dataset.describe()

               Label
count  421749.000000
mean        0.185070
std         0.388355
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000

In [23]:
dataset['labels']= dataset['Label'].map({0:'Hate speech',1:'offencive language',2:'No hate or offencive language'})

In [24]:
dataset

,Content,Label,labels
0,denial of normal the con be asked to comment o...,1.0,offencive language
1,just by being able to tweet this insufferable ...,1.0,offencive language
2,that is retarded you too cute to be single tha...,1.0,offencive language
3,thought of a real badass mongol style declarat...,1.0,offencive language
4,afro american basho,1.0,offencive language
...,...,...,...
421745,utc name change the article has been changed t...,0.0,Hate speech
421746,charles sumner article hello dr jensen i have ...,0.0,Hate speech
421747,and i really appreciate you for this i have to...,0.0,Hate speech
421748,copyright hi moran i wanted to talk to you abo...,0.0,Hate speech
421749,wikipediaarticles for deletion list of plants ...,NaN,NaN

In [25]:
data=dataset[['Content','labels']]

In [26]:
data

                                                  Content              labels
0       denial of normal the con be asked to comment o...  offencive language
1       just by being able to tweet this insufferable ...  offencive language
2       that is retarded you too cute to be single tha...  offencive language
3       thought of a real badass mongol style declarat...  offencive language
4                                     afro american basho  offencive language
...                                                   ...                 ...
421745  utc name change the article has been changed t...         Hate speech
421746  charles sumner article hello dr jensen i have ...         Hate speech
421747  and i really appreciate you for this i have to...         Hate speech
421748  copyright hi moran i wanted to talk to you abo...         Hate speech
421749  wikipediaarticles for deletion list of plants ...                 NaN

[421750 rows x 2 columns]

In [27]:
import re
import nltk

In [30]:
from nltk.corpus import stopwords
stopwords=set(stopwords.words('english'))

LookupError:
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')

  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - '/root/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

In [ ]:
import nltk
nltk.download('stopwords')

In [ ]:
stemmer=nltk.SnowballStemmer('english')

In [ ]:
#cleaing data
import string
def clean_data(text):
    text = str(text).lower()
    text = re.sub("https?://\S+|www\.\S+", "", text)
    text = re.sub("\[.*?\]", "", text)
    text = re.sub("<.*?>", "", text)
    text = re.sub("[%s]" % re.escape(string.punctuation), "", text)
    text = re.sub("\n","", text)
    text = re.sub("\w*\d\w*", "", text)

    # Stop words removal
    text = [word for word in text.split() if word not in stopwords]
    text = " ".join(text)

    # Stemming the text
    text = [stemmer.stem(word) for word in text.split()]
    text = " ".join(text)
    return text

In [ ]:
data['Content']=data['Content'].apply(clean_data)

In [ ]:
data

In [ ]:
x = np.array(data['Content'])
y=  np.array(data['labels'])

In [ ]:
x

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
cv = CountVectorizer()
x = cv.fit_transform(x)

In [ ]:
x

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [ ]:
from sklearn.naive_bayes import MultinomialNB

# Initialize the Multinomial Naive Bayes model
model = MultinomialNB()

# Train the model using the training data
model.fit(X_train, y_train)

In [ ]:
#Building out Model
from sklearn.tree import DecisionTreeClassifier

In [ ]:
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

In [ ]:
y_pred= dt.pridict(x_test)

In [ ]:
#Confusion matrix and accuracy
from sklearn.metrics import accuracy_score, confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

In [ ]:
import seaborn as sns
sns.heatmap(cm,annot=True,fmt='f',cmap='YIGnBu')

In [ ]:
from sklearn.matrics import accuracy_score
accuracy_score(y_test,y_pred)

In [ ]:
sample = 'lets unite and kill all the people who are protesting against the government'
sample=clean_data(sample)

In [ ]:
sample

In [ ]:
data1=cv.transform([sample]).toarray()

In [ ]:
data1

In [ ]:
dt.pridict(data1)